class AppConfig:
    # Modern Aesthetic Theme
    BG_COLOR = "#1a1a2e"
    FRAME_COLOR = "#16213e"
    ACCENT_COLOR = "#7c3aed"
    TEXT_COLOR = "#e2e8f0"
    HOVER_COLOR = "#6d28d9"
    SURFACE_COLOR = "#1e293b"
    BORDER_COLOR = "#334155"
    MUTED_COLOR = "#94a3b8"

    DEFAULT_DEPTH = 15
    DEFAULT_SCREENSHOT_DELAY = 0.4
    DEFAULT_MOVE_MODE = "drag"

    OPPONENT_MOVE_SETTLE_DELAY = 0.5
    AUTO_MODE_POLL_INTERVAL = 0.1
    MAX_FEN_EXTRACTION_RETRIES = 5
    FEN_RETRY_DELAY = 0.2
    MIN_MOVE_INTERVAL = 0.3
    MAX_CONSECUTIVE_FAILURES = 3
    SKIP_VERIFICATION_ON_FAILURE = True
    BOARD_DETECTION_CONFIDENCE = 0.5

    HUMAN_MOVE_MIN_DURATION = 0.15
    HUMAN_MOVE_MAX_DURATION = 0.45
    HUMAN_THINK_MIN_DELAY = 0.3
    HUMAN_THINK_MAX_DELAY = 1.5

    WINDOW_TITLE = "RAMURI"
    WINDOW_WIDTH = 400
    WINDOW_HEIGHT = 600
